### ISSUE TITLE
Delphi程序优化需求 - 20200202

### ISSUE THREAD

**Issue by tiangao-bit** [CloudLab-BIT/delphi5-single#2]
1．界面优化
1.1引导操作人员完成实验
主要通过下面两部分界面，通过上一步下一步按钮进行不同的实验步骤，通过不同的显示界面来实现引导人员操作并完成试验的目的。

1.2归零操作简化 
将电缸位置，角度，扭矩归零操作设置为一步（单独调零按钮也保存）。

1.3去除与当前步骤无关显示内容
    简化界面显示.无关按钮和功能不需显示。如在第二界面中无需显示手动伸出，缩回功能按钮和归零按钮。

2．功能优化
2.1原版程序功能不能删减

2.2增加预测功能
在不同界面中显示不同的预测值，在第一界面中显示预估试验参数，工作应变范围，工作应力范围，理论最大转角，应变率，材料剪切模量推荐值。在第二界面中显示预测寿命，预测剩余次数以及剩余试验时间。

2.3设置周期采样点数
在设置参数中新增设置每周期采样点数功能，能够手动输入每一周期采样点。

2.4增加试验加载数据、试棒信息数据记录功能
每一次试验保存两类数据文件，第一类文件为试验试棒和加载参数文件，第二类文件为采集到的试验数据文件。

**Comment by StoneGo** [comment]
![Delphi-opt](https://user-images.githubusercontent.com/10358582/73609022-7ed62b80-4604-11ea-96d0-18231d27fca8.png)

**Comment by StoneGo** [comment]
Updated By #3

**Comment by LOKI2020-bit** [comment]
（1）用demo或GUI的形式，将需要开发或修改或补充的功能进行图形界面模式描述；
（2）主要的功能是扭矩/角位移等传感器标定/归零；实时数据采集；延时/实时（每五分钟数据文件/每个加载循环的160-320个点）数据处理；寿命预测算法/模型；原始数据的保存与清洗提炼。
（3）现有delphi程序的不合理或不完善的功能，要先列表进行罗列汇总；
（4）现有程序各个功能模块的掌握程度（硬件通信接口）、函数的流程图（软件实现逻辑）；
（5）功能模块的开发计划、责任人与时间节点；
细化完善需求文档。这个文档是后续开发的标准文件。
